[project]
name = "pyproject"
version = "0.1.0"
description = "testing dependencies"
authors = [
    {name = "Szyn"}
]
readme = "README.md"
requires-python = "^3.10.12"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
